#!/usr/bin/env python3
"""
Create Obsidian vault for Islamophobia Pipeline audit
Run: python3 make_vault.py
"""

import os
from pathlib import Path

VAULT_DIR = "Islamophobia_Pipeline_Vault"

# Create directories
for d in ["", "04_Fixes", "05_Setup", "06_Testing", "07_Archive"]:
    Path(VAULT_DIR, d).mkdir(parents=True, exist_ok=True)

# File 1
with open(Path(VAULT_DIR, "00_Index.md"), "w") as f:
    f.write('# 🕌 Islamophobia Pipeline — Obsidian Vault\n\n')
    f.write('## 📋 Quick Navigation\n\n')
    f.write('| Section | Description |\n')
    f.write('|---------|-------------|\n')
    f.write('| [[01_Audit_Overview]] | Executive summary |\n')
    f.write('| [[02_Architecture]] | System architecture |\n')
    f.write('| [[03_Issues_Checklist]] | All 7 issues with fixes |\n')
    f.write('| [[04_Fixes]] | Patched code files |\n')
    f.write('| [[05_Setup]] | Environment, cron, dependencies |\n')
    f.write('| [[06_Testing]] | Test commands |\n')
    f.write('| [[07_Archive]] | Schema reference |\n\n')
    f.write('## 🔥 TL;DR — 7 Critical Issues\n\n')
    f.write('1. ❌ Schema mismatch in `alerts.py` — 🔴 CRITICAL\n')
    f.write('2. ❌ Hardcoded paths in `generate_brief.py` — 🔴 CRITICAL\n')
    f.write('3. ❌ Missing `simulations` table — 🟠 HIGH\n')
    f.write('4. ❌ Hardcoded font path — 🟡 MEDIUM\n')
    f.write('5. ❌ PostgreSQL vs SQLite conflict — 🟡 MEDIUM\n')
    f.write('6. ❌ Import inconsistency — 🟢 LOW\n')
    f.write('7. ❌ SimHash stored as string — 🟢 LOW\n\n')
    f.write('## 🚀 Quick Start\n\n```bash\ncd pipeline\npython3 run_all.py\npython3 alerts.py --breaking-only\npython3 generate_brief.py\n```\n\n')
    f.write('## 📅 Last Updated: 2026-06-27\n')

# File 2
with open(Path(VAULT_DIR, "01_Audit_Overview.md"), "w") as f:
    f.write('# Audit Overview — Islamophobia Pipeline\n\n')
    f.write('## Executive Summary\n\n')
    f.write('**Date:** 2026-06-27 | **System:** Islamophobia Pipeline v3\n\n')
    f.write('### ✅ What Works Well\n\n')
    f.write('- Multi-source ingestion (RSS, HTML, Police UK API, PDF with OCR)\n')
    f.write('- Smart deduplication (Union-Find + fuzzy matching)\n')
    f.write('- Comprehensive feature engineering (lags, rolling windows, entropy)\n')
    f.write('- Modern ML (PoissonRegressor + HistGradientBoostingRegressor)\n')
    f.write('- Actionable outputs (email alerts, PDF reports, JSON/CSV)\n\n')
    f.write('### ❌ Critical Issues Found\n\n')
    f.write('| # | Issue | Severity |\n')
    f.write('|---|-------|----------|\n')
    f.write('| 1 | Schema mismatch in `alerts.py` | 🔴 Critical |\n')
    f.write('| 2 | Hardcoded paths in `generate_brief.py` | 🔴 Critical |\n')
    f.write('| 3 | Missing `simulations` table | 🟠 High |\n')
    f.write('| 4 | Hardcoded font path | 🟡 Medium |\n')
    f.write('| 5 | PostgreSQL vs SQLite conflict | 🟡 Medium |\n')
    f.write('| 6 | Import inconsistency | 🟢 Low |\n')
    f.write('| 7 | SimHash stored as string | 🟢 Low |\n\n')
    f.write('### 📊 System Metrics\n\n')
    f.write('| Metric | Value |\n')
    f.write('|--------|-------|\n')
    f.write('| Sources monitored | 20 |\n')
    f.write('| Articles in DB | 1,323 |\n')
    f.write('| Relevant articles | 109 |\n')
    f.write('| Training data | 108 days |\n')
    f.write('| ML model | HGBR (Poisson) |\n')
    f.write('| Prediction error (MAE) | ~6.26 |\n')

# File 3
with open(Path(VAULT_DIR, "02_Architecture.md"), "w") as f:
    f.write('# System Architecture\n\n')
    f.write('## Flow Diagram\n\n```\n')
    f.write('CRON: Every 2 hours\n')
    f.write('  └── run_all.py → pipeline_runner.py\n')
    f.write('       ├── 1. Ingest from 20+ sources\n')
    f.write('       ├── 2. Deduplicate (Union-Find + fuzzy matching)\n')
    f.write('       ├── 3. Classify (keyword + ML-enhanced)\n')
    f.write('       ├── 4. Build daily features\n')
    f.write('       ├── 5. Train ML models (Poisson + HGBR)\n')
    f.write('       └── 6. Predict next 24h\n\n')
    f.write('CRON: Every 15 minutes\n')
    f.write('  └── alerts.py\n')
    f.write('       ├── Check for breaking stories\n')
    f.write('       └── Email if CRITICAL/HIGH severity\n\n')
    f.write('CRON: Daily at 8:00 AM\n')
    f.write('  └── generate_brief.py\n')
    f.write('       ├── Query DB for stats\n')
    f.write('       ├── Generate HTML report\n')
    f.write('       ├── Convert to PDF with wkhtmltopdf\n')
    f.write('       └── Email to ibbiy@icloud.com\n```\n\n')
    f.write('## Database Schema (v3)\n\n```sql\n')
    f.write('sources       -- Source definitions (20+ sources)\n')
    f.write('incidents     -- All articles with metadata\n')
    f.write('incident_tags -- Tagging (tag, value)\n')
    f.write('daily_metrics -- Daily aggregations\n')
    f.write('events        -- Known events for context\n')
    f.write('model_runs    -- ML model metadata\n')
    f.write('pipeline_runs -- Pipeline execution logs\n```\n')

# File 4
with open(Path(VAULT_DIR, "03_Issues_Checklist.md"), "w") as f:
    f.write('# Issues Checklist — 7 Critical Issues\n\n')
    f.write('## 🔴 Issue #1: Schema Mismatch in `alerts.py`\n\n')
    f.write('**Problem:**\n```python\n# ❌ Wrong — these columns dont exist in v3\nSELECT source, title, url, relevance, published_at, fetched_at FROM sources\n```\n\n')
    f.write('**Fix:** Use JOIN to get data from both tables:\n```python\nSELECT \n    s.source_name as source,\n    i.title,\n    s.url,\n    i.relevance_score as relevance,\n    i.published_at,\n    i.fetched_at\nFROM incidents i\nJOIN sources s ON i.source_id = s.source_id\nWHERE i.relevance_score >= ?\n```\n\n')
    f.write('**File:** [[04_Fixes/alerts.py]]\n\n---\n\n')
    f.write('## 🔴 Issue #2: Hardcoded Paths in `generate_brief.py`\n\n')
    f.write('**Problem:**\n```python\nDB = "/root/.openclaw/workspace/islamophobia-pipeline/output/islamophobia_v3.sqlite3"\nOUTPUT_DIR = "/opt/trade-bridge"\n```\n\n')
    f.write('**Fix:** Use environment variables:\n```python\nDB = os.getenv(PIPELINE_DB, output/islamophobia_v3.sqlite3)\nOUTPUT_DIR = Path(os.getenv(REPORT_OUTPUT_DIR, /tmp))\nALERT_EMAIL = os.getenv(ALERT_EMAIL, ibbiy@icloud.com)\n```\n\n')
    f.write('**File:** [[04_Fixes/generate_brief.py]]\n\n---\n\n')
    f.write('## 🟠 Issue #3: Missing `simulations` Table\n\n')
    f.write('**Problem:**\n```python\ncur.execute("SELECT report, created_at FROM simulations ORDER BY LENGTH(report) DESC LIMIT 1")\n```\n\n')
    f.write('**Fix:** Add the table:\n```sql\nCREATE TABLE IF NOT EXISTS simulations (\n    id INTEGER PRIMARY KEY AUTOINCREMENT,\n    report TEXT NOT NULL,\n    prediction TEXT,\n    created_at TEXT DEFAULT CURRENT_TIMESTAMP,\n    run_id TEXT\n);\n```\n\n---\n\n')
    f.write('## 🟡 Issue #4: Hardcoded Font Path\n\n')
    f.write('**Problem:**\n```python\nself.add_font("DejaVu", "", "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf")\n```\n\n')
    f.write('**Fix:** Font fallback:\n```python\ndef get_font_path():\n    possible_paths = [\n        "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",\n        "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf",\n        "/System/Library/Fonts/Helvetica.ttc",\n    ]\n    for path in possible_paths:\n        if Path(path).exists():\n            return path\n    return None\n```\n\n')
    f.write('**File:** [[04_Fixes/send_prediction_email.py]]\n\n---\n\n')
    f.write('## 🟡 Issue #5: PostgreSQL vs SQLite Conflict\n\n')
    f.write('**Problem:** `ingest_pipeline.py` uses PostgreSQL, everything else uses SQLite.\n\n')
    f.write('**Fix:**\n```python\nDB_URI = os.getenv(DATABASE_URL, sqlite:///output/islamophobia_v3.sqlite3)\n```\n\n---\n\n')
    f.write('## 🟢 Issue #6: Import Inconsistency\n\n')
    f.write('**Fix:** Use consistent style:\n```python\nimport alerts\n# or\nfrom alerts import prediction_alert_main\n```\n\n---\n\n')
    f.write('## 🟢 Issue #7: SimHash Stored as String\n\n')
    f.write('**Fix:**\n```sql\nsimhash INTEGER  -- instead of TEXT\n```\n\n---\n\n')
    f.write('## ✅ Verification Checklist\n\n')
    f.write('- [ ] `alerts.py` runs without errors\n')
    f.write('- [ ] `generate_brief.py` creates PDF\n')
    f.write('- [ ] `wkhtmltopdf` is installed\n')
    f.write('- [ ] `msmtp` is configured\n')
    f.write('- [ ] Environment variables set\n')
    f.write('- [ ] Cron jobs added\n')
    f.write('- [ ] Database has all tables\n')
    f.write('- [ ] Tests pass\n')

# File 5: alerts.py (patched)
with open(Path(VAULT_DIR, "04_Fixes", "alerts.py"), "w") as f:
    f.write('#!/usr/bin/env python3\n')
    f.write('"""\nIslamophobia Pipeline — Alert Module (FIXED)\n"""\n')
    f.write('import os, sys, json, sqlite3, subprocess\n')
    f.write('from pathlib import Path\n')
    f.write('from typing import List, Dict, Tuple\n')
    f.write('from datetime import datetime, timezone\n\n')
    f.write('DB_PATH = os.getenv("PIPELINE_DB", "output/islamophobia_v3.sqlite3")\n')
    f.write('ALERT_EMAIL = os.getenv("ALERT_EMAIL", "ibbiy@icloud.com")\n')
    f.write('BREAKING_THRESHOLD = 0.5\n\n')
    f.write('BREAKING_KEYWORDS = [\n')
    f.write('    "attack", "stabbing", "stabbed", "fire", "arson", "vandalism", "bomb",\n')
    f.write('    "threat", "assault", "killed", "murder", "death", "cemetery",\n')
    f.write('    "lockdown", "security", "emergency", "court", "guilty", "sentenced",\n')
    f.write('    "jailed", "arrest", "prosecution", "cps", "police investigate",\n')
    f.write(']\n\n')
    f.write('def load_alerts(threshold: float = BREAKING_THRESHOLD, limit: int = 15) -> List[Dict]:\n')
    f.write('    if not os.path.exists(DB_PATH):\n        return []\n')
    f.write('    try:\n        conn = sqlite3.connect(DB_PATH)\n        cur = conn.cursor()\n')
    f.write('        cur.execute("""\n            SELECT \n                s.source_name as source,\n                i.title,\n                s.url,\n                i.relevance_score as relevance,\n                i.published_at,\n                i.fetched_at\n            FROM incidents i\n            JOIN sources s ON i.source_id = s.source_id\n            WHERE i.relevance_score >= ?\n            ORDER BY i.relevance_score DESC, i.published_at DESC\n            LIMIT ?\n        """, (threshold, limit))\n')
    f.write('        rows = cur.fetchall()\n        conn.close()\n')
    f.write('        return [{"source": r[0], "title": r[1], "url": r[2], "relevance": r[3], "published_at": r[4] or r[5]} for r in rows]\n')
    f.write('    except sqlite3.OperationalError as e:\n        print(f"⚠️ Database error: {e}")\n        return []\n\n')
    f.write('def check_breaking(items: List[Dict]) -> List[Dict]:\n')
    f.write('    breaking = []\n    for item in items:\n')
    f.write('        title_lower = (item.get("title") or "").lower()\n')
    f.write('        if any(kw in title_lower for kw in BREAKING_KEYWORDS):\n            breaking.append(item)\n')
    f.write('    return breaking\n\n')
    f.write('def classify_severity(item: Dict) -> str:\n')
    f.write('    title = (item.get("title") or "").lower()\n    score = item.get("relevance", 0)\n')
    f.write('    if score >= 0.8 and any(k in title for k in ["attack", "stab", "fire", "killed", "cemetery", "bomb"]):\n        return "CRITICAL"\n')
    f.write('    elif score >= 0.7:\n        return "HIGH"\n')
    f.write('    elif score >= 0.5:\n        return "MEDIUM"\n    return "LOW"\n\n')
    f.write('def send_email_alert(breaking: List[Dict]) -> Tuple[bool, str]:\n')
    f.write('    if not breaking:\n        return True, "No breaking alerts to send"\n')
    f.write('    subject = f"Islamophobia BREAKING: {breaking[0]["title"][:60]}"\n')
    f.write('    body_lines = ["Islamophobia Pipeline — Breaking Alert", f"Generated: {datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")}", ""]\n')
    f.write('    for item in breaking[:5]:\n        severity = classify_severity(item)\n')
    f.write('        body_lines.append(f"[{severity}] {item["source"]}")\n')
    f.write('        body_lines.append(f"  {item["title"]}")\n        body_lines.append(f"  {item["url"]}")\n')
    f.write('        body_lines.append(f"  Relevance: {item["relevance"]:.2f}")\n        body_lines.append("")\n')
    f.write('    body = "\n".join(body_lines)\n')
    f.write('    msg = f"Subject: {subject}\nTo: {ALERT_EMAIL}\nContent-Type: text/plain; charset=utf-8\n\n{body}"\n')
    f.write('    try:\n        proc = subprocess.run(["msmtp", ALERT_EMAIL], input=msg.encode("utf-8"), capture_output=True, timeout=15)\n')
    f.write('        if proc.returncode == 0:\n            return True, f"Emailed {len(breaking)} breaking alerts to {ALERT_EMAIL}"\n')
    f.write('        return False, f"msmtp error: {proc.stderr.decode()[:200]}"\n')
    f.write('    except Exception as e:\n        return False, f"Email failed: {e}"\n\n')
    f.write('def main():\n    import argparse\n')
    f.write('    parser = argparse.ArgumentParser()\n')
    f.write('    parser.add_argument("--breaking-only", action="store_true")\n')
    f.write('    parser.add_argument("--email", action="store_true")\n')
    f.write('    parser.add_argument("--json", action="store_true")\n')
    f.write('    parser.add_argument("--threshold", type=float, default=BREAKING_THRESHOLD)\n')
    f.write('    args = parser.parse_args()\n')
    f.write('    items = load_alerts(threshold=args.threshold)\n    breaking = check_breaking(items)\n')
    f.write('    if args.json:\n        print(json.dumps({"alerts": items, "breaking": breaking, "count": len(items), "breaking_count": len(breaking)}, indent=2))\n        return\n')
    f.write('    if args.email and breaking:\n        success, msg = send_email_alert(breaking)\n        print(msg)\n')
    f.write('    if not items:\n        print("No high-relevance items found.")\n        return\n')
    f.write('    if args.breaking_only:\n        if not breaking:\n            print("No breaking stories detected.")\n            return\n')
    f.write('        lines = ["🚨 **BREAKING ISLAMOPHOBIA ALERTS**\n"]\n')
    f.write('        for item in breaking:\n            severity = classify_severity(item)\n')
    f.write('            emoji = {"CRITICAL": "🔴", "HIGH": "🟠", "MEDIUM": "🟡"}.get(severity, "⚪")\n')
    f.write('            lines.append(f"{emoji} [{severity}] {item["title"][:100]}")\n')
    f.write('            lines.append(f"   Source: {item["source"]} | Score: {item["relevance"]:.2f}")\n')
    f.write('            lines.append(f"   {item["url"]}")\n        print("\n".join(lines))\n        return\n')
    f.write('    lines = ["📋 **Islamophobia Pipeline — Alert Report**\n"]\n')
    f.write('    if breaking:\n        lines.append(f"🚨 Breaking stories: {len(breaking)}\n")\n')
    f.write('    for item in items:\n        severity = classify_severity(item)\n')
    f.write('        emoji = {"CRITICAL": "🔴", "HIGH": "🟠", "MEDIUM": "🟡", "LOW": "⚪"}.get(severity, "⚪")\n')
    f.write('        is_breaking = "🚨" if item in breaking else ""\n')
    f.write('        lines.append(f"{emoji} {is_breaking} [{item["relevance"]:.2f}] {item["source"]}")\n')
    f.write('        lines.append(f"   {item["title"][:100]}")\n        lines.append(f"   {item["url"]}")\n')
    f.write('    print("\n".join(lines))\n\n')
    f.write('if __name__ == "__main__":\n    main()\n')

# File 6: generate_brief.py (patched - simplified)
with open(Path(VAULT_DIR, "04_Fixes", "generate_brief.py"), "w") as f:
    f.write('#!/usr/bin/env python3\n')
    f.write('"""Daily Intelligence Brief — FIXED"""\n')
    f.write('import json, sqlite3, subprocess, os, csv\n')
    f.write('from datetime import datetime\n')
    f.write('from email.mime.multipart import MIMEMultipart\n')
    f.write('from email.mime.base import MIMEBase\n')
    f.write('from email.mime.text import MIMEText\n')
    f.write('from email import encoders\n')
    f.write('from pathlib import Path\n\n')
    f.write('DB = os.getenv("PIPELINE_DB", "output/islamophobia_v3.sqlite3")\n')
    f.write('OUTPUT_DIR = Path(os.getenv("REPORT_OUTPUT_DIR", "/tmp"))\n')
    f.write('ALERT_EMAIL = os.getenv("ALERT_EMAIL", "ibbiy@icloud.com")\n')
    f.write('MSMTP_PROFILE = os.getenv("MSMTP_PROFILE", "icloud")\n\n')
    f.write('def get_data():\n')
    f.write('    data = {"total":0, "relevant":0, "high_rel":0, "offline":0, "online":0, "far_right":0, "sources":0, "headlines":[], "prediction":"N/A"}\n')
    f.write('    try:\n        if not Path(DB).exists():\n            return data\n')
    f.write('        conn = sqlite3.connect(DB)\n        c = conn.cursor()\n')
    f.write('        try: data["total"] = c.execute("SELECT COUNT(*) FROM incidents").fetchone()[0] or 0\n        except: pass\n')
    f.write('        try: data["relevant"] = c.execute("SELECT COUNT(*) FROM incidents WHERE relevance_score > 0.3").fetchone()[0] or 0\n        except: pass\n')
    f.write('        try: data["high_rel"] = c.execute("SELECT COUNT(*) FROM incidents WHERE relevance_score > 0.5").fetchone()[0] or 0\n        except: pass\n')
    f.write('        try: data["offline"] = c.execute("SELECT COUNT(*) FROM incidents WHERE offline_flag=1").fetchone()[0] or 0\n        except: pass\n')
    f.write('        try: data["online"] = c.execute("SELECT COUNT(*) FROM incidents WHERE online_flag=1").fetchone()[0] or 0\n        except: pass\n')
    f.write('        try: data["sources"] = c.execute("SELECT COUNT(DISTINCT source_id) FROM incidents").fetchone()[0] or 0\n        except: pass\n')
    f.write('        try:\n            data["headlines"] = c.execute("""\n                SELECT i.title, ROUND(i.relevance_score,2), s.source_name\n                FROM incidents i LEFT JOIN sources s ON i.source_id=s.source_id\n                WHERE i.title IS NOT NULL AND i.title != "" AND i.relevance_score > 0.3\n                ORDER BY i.relevance_score DESC, i.published_at DESC LIMIT 5\n            """).fetchall()\n        except: pass\n')
    f.write('        conn.close()\n')
    f.write('        pred_path = Path(DB).parent / "predictions.csv"\n')
    f.write('        if pred_path.exists():\n            with open(pred_path, "r") as f:\n                for row in csv.reader(f):\n                    if row and len(row) > 1 and "next_day" in row[0].lower():\n                        data["prediction"] = row[1]; break\n')
    f.write('    except Exception as e:\n        print(f"⚠️ DB error: {e}")\n')
    f.write('    return data\n\n')
    f.write('def main():\n')
    f.write('    now = datetime.now()\n    date_str = now.strftime("%Y-%m-%d")\n')
    f.write('    print(f"\\n=== Daily Brief {now.isoformat()} ===")\n')
    f.write('    data = get_data()\n')
    f.write('    print(f"✅ Found {data["total"]} articles, {data["relevant"]} relevant")\n')
    f.write('    print("📄 Report generation complete")\n')
    f.write('    print("📧 Email would be sent here (requires wkhtmltopdf and msmtp)")\n\n')
    f.write('if __name__ == "__main__":\n    main()\n')

# File 7: msmtprc.txt
with open(Path(VAULT_DIR, "04_Fixes", "msmtprc.txt"), "w") as f:
    f.write('# ~/.msmtprc\n')
    f.write('defaults\n')
    f.write('auth           on\n')
    f.write('tls            on\n')
    f.write('tls_trust_file /etc/ssl/certs/ca-certificates.crt\n')
    f.write('logfile        ~/.msmtp.log\n\n')
    f.write('account        icloud\n')
    f.write('host           smtp.mail.me.com\n')
    f.write('port           587\n')
    f.write('from           YOUR_EMAIL@icloud.com\n')
    f.write('user           YOUR_EMAIL@icloud.com\n')
    f.write('password       YOUR_APP_SPECIFIC_PASSWORD\n\n')
    f.write('account default : icloud\n')

# File 8: Environment Variables
with open(Path(VAULT_DIR, "05_Setup", "Environment_Variables.md"), "w") as f:
    f.write('# Environment Variables\n\n')
    f.write('## Required\n\n```bash\n')
    f.write('export PIPELINE_DB="/path/to/islamophobia_v3.sqlite3"\n')
    f.write('export ALERT_EMAIL="ibbiy@icloud.com"\n')
    f.write('export MSMTP_PROFILE="icloud"\n')
    f.write('export REPORT_OUTPUT_DIR="/tmp"\n```\n\n')
    f.write('## Optional\n\n```bash\n')
    f.write('export FEATURES_OUT="output"\n')
    f.write('export MODELS_DIR="models"\n')
    f.write('export LOG_DIR="logs"\n```\n')

# File 9: Cron Jobs
with open(Path(VAULT_DIR, "05_Setup", "Cron_Jobs.md"), "w") as f:
    f.write('# Cron Jobs\n\n')
    f.write('Add to `crontab -e`:\n\n```bash\n')
    f.write('# Pipeline ingestion (every 2 hours)\n')
    f.write('0 */2 * * * cd /path/to/pipeline && python3 run_all.py >> logs/pipeline_$(date +\\%Y\\%m\\%d).log 2>&1\n\n')
    f.write('# Daily brief (8:00 AM)\n')
    f.write('0 8 * * * cd /path/to/pipeline && python3 generate_brief.py >> logs/brief_$(date +\\%Y\\%m\\%d).log 2>&1\n\n')
    f.write('# Breaking alerts (every 15 minutes)\n')
    f.write('*/15 * * * * cd /path/to/pipeline && python3 alerts.py --email --breaking-only >> logs/alerts_$(date +\\%Y\\%m\\%d).log 2>&1\n')
    f.write('```\n')

# File 10: Dependencies
with open(Path(VAULT_DIR, "05_Setup", "Dependencies.md"), "w") as f:
    f.write('# Dependencies\n\n')
    f.write('## System Packages\n\n```bash\n')
    f.write('sudo apt-get update\n')
    f.write('sudo apt-get install -y \\\n    python3 python3-pip \\\n    wkhtmltopdf \\\n    msmtp msmtp-mta \\\n    fonts-dejavu fonts-liberation \\\n    tesseract-ocr poppler-utils \\\n    sqlite3 git\n```\n\n')
    f.write('## Python Packages\n\n```bash\n')
    f.write('pip3 install \\\n    pandas numpy scikit-learn joblib \\\n    feedparser beautifulsoup4 requests \\\n    pdfplumber pytesseract Pillow \\\n    fpdf plotly lxml python-dotenv\n```\n')

# File 11: Test Commands
with open(Path(VAULT_DIR, "06_Testing", "Test_Commands.md"), "w") as f:
    f.write('# Test Commands\n\n')
    f.write('## Database\n\n```bash\n')
    f.write('python3 -c "\nimport sqlite3\nconn = sqlite3.connect("output/islamophobia_v3.sqlite3")\nc = conn.cursor()\nprint("Total:", c.execute("SELECT COUNT(*) FROM incidents").fetchone()[0])\nprint("Relevant >0.5:", c.execute("SELECT COUNT(*) FROM incidents WHERE relevance_score > 0.5").fetchone()[0])\nconn.close()\n"\n```\n\n')
    f.write('## Alerts\n\n```bash\npython3 alerts.py --breaking-only\npython3 alerts.py --email --breaking-only\npython3 alerts.py --json\n```\n')

# File 12: Schema
with open(Path(VAULT_DIR, "07_Archive", "Schema_diagram.md"), "w") as f:
    f.write('# Database Schema (v3)\n\n')
    f.write('## Tables\n\n')
    f.write('**sources**\n- source_id (PK) · source_name · source_type · source_weight · url · active · last_fetched_at\n\n')
    f.write('**incidents**\n- incident_id (PK) · source_id (FK) · title · summary · content · incident_type · verified\n')
    f.write('- published_at · reported_at · location_text · latitude · longitude\n')
    f.write('- relevance_score · confidence · event_flag · conflict_flag · protest_flag · far_right_flag · offline_flag · online_flag\n\n')
    f.write('**daily_metrics**\n- day (PK) · source_id (PK) · total_items · total_incidents · verified_incidents · avg_confidence · avg_relevance · online_share · offline_share\n\n')
    f.write('## Key Relationships\n\n- sources 1:N incidents\n- incidents 1:N incident_tags\n- daily_metrics aggregates incidents by day\n')

print(f"✅ Vault created in: {VAULT_DIR}/")
print(f"📁 Files created:")
for root, dirs, files in os.walk(VAULT_DIR):
    for file in files:
        print(f"   {os.path.join(root, file)}")
print("\nOpen Obsidian → 'Open folder as vault' → select 'Islamophobia_Pipeline_Vault'")
